# 批处理

In [11]:
%run ./neuralnet_mnist.ipynb
x,t = get_data()
network = init_network()
batch_size = 100 #数量
accuracy_cnt = 0
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network,x_batch)
    p = np.argmax(y_batch,axis=1)
    accuracy_cnt +=np.sum(p== t[i:i+batch_size])
print("Accuracy:"+str(float(accuracy_cnt)/len(x)))

Creating pickle file ...
Done!
Accuracy:0.9352
Accuracy:0.9352


In [13]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
x = np.array([[0.1,0.8,0.1],[0.3,0.1,0.6],[0.2,0.5,0.3],[0.8,0.1,0.1]])
print(x)

[[0.1 0.8 0.1]
 [0.3 0.1 0.6]
 [0.2 0.5 0.3]
 [0.8 0.1 0.1]]


In [17]:
y = np.argmax(x,axis=1)
print(y)

[1 2 1 0]
